# Site settings
url: "https://www.www.stephanie.wine"
name: 'Stephanie.Wine'

# Meta
title: "Stephanie.Wine"
subtitle: "“Wine can of their wits the wise beguile, Make the sage frolic, and the serious smile” ― Homer"
description: "Stephanie.Wine Homepage"

# Links
email: hello@stephanie.wine
instagram: stephanie.wine

# Images
avatar: yes
avatar_img_path: "imgs/avatar.jpeg"
front_img: yes
front_img_path: "imgs/background.jpeg"
favicon_img: yes
favicon_img_path: "imgs/favicon.ico"

# Build settings
markdown: kramdown
permalink: pretty

exclude: ["LICENSE", README.md]
